development:
  adapter: sqlserver
  host: 192.168.1.6
  database: portal_dev
  username: portal_user
  password: portal_user7531

test:
  adapter: sqlserver
  host: 192.168.1.6
  database: portal_test
  username: portal_user
  password: portal_user7531

production:
  adapter: sqlserver
  host: 192.168.1.6
  database: portal_dev
  username: portal_user
  password: portal_user7531
